### ISSUE TITLE
Decision to be made on upgrading `scikit-learn` and `numpy`

### ISSUE THREAD

**Issue by maxbriel** [POSYDON-code/POSYDON-public#384]
When installing the latest version of development, POSYDON installs but cannot run when the active-learning is loaded.
The following error is thrown: 

```
  File "/srv/astro/projects/posydon/software/conda_envs/posydon_240913/lib/python3.11/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/srv/astro/projects/posydon/software/conda_envs/posydon_240913/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 19, in <module>
    from .murmurhash import murmurhash3_32
  File "sklearn/utils/murmurhash.pyx", line 1, in init sklearn.utils.murmurhash
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

A search indicates that this is an issue with scikit-learn and numpy.
It looks like a too new version of numpy is installed (>=2.x.x) for the scikit-learn version (1.2.2).

A limit should be set on which numpy version is installed or scikit-learn should be updated.

**Comment by ka-rocha** [comment]
When you say active learning is loaded could you specify what / where this is happening? If it is just an issue with old scikit-learn then I think a reasonable solution would be to move to a new version.

**Comment by maxbriel** [comment]
So this happened when I tried to run `posydon-setup-grid` on a fresh installation/environment of POSYDON. The script loads in components of POSYDON, but also loads in the active learning sub-module. There were no errors during the installation.
We have a limiting dependency for scikit-learn to <=1.2.2, but it does not have an upper limit dependency on numpy (as far as I can see). But I found that only scikit-learn >= 1.5 support numpy >= 2. 

Can we just update scikit-learn or will there be issues with changing methods or our interpolator objects?

Here's a full traceback when running it locally.
```
  __import__('pkg_resources').require('posydon==1.0.0+261.g251b3c6')
Traceback (most recent call last):
  File "/Users/max/Desktop/install_test/conda/bin/posydon-run-grid", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/max/Desktop/install_test/POSYDON/bin/posydon-run-grid", line 21, in <module>
    from posydon.active_learning.psy_cris.utils import parse_inifile
  File "/Users/max/Desktop/install_test/POSYDON/posydon/active_learning/psy_cris/utils.py", line 16, in <module>
    from sklearn.neighbors import NearestNeighbors
  File "/Users/max/Desktop/install_test/conda/lib/python3.11/site-packages/sklearn/__init__.py", line 82, in <module>
    from .base import clone
  File "/Users/max/Desktop/install_test/conda/lib/python3.11/site-packages/sklearn/base.py", line 17, in <module>
    from .utils import _IS_32BIT
  File "/Users/max/Desktop/install_test/conda/lib/python3.11/site-packages/sklearn/utils/__init__.py", line 19, in <module>
    from .murmurhash import murmurhash3_32
  File "sklearn/utils/murmurhash.pyx", line 1, in init sklearn.utils.murmurhash
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by ka-rocha** [comment]
I see! I am in favor of upgrading scikit-learn but know less if this will break some interpolation things. @philipp-rajah Can you comment about if you need specific versions of this package?

**Comment by philipp-rajah** [comment]
I've just gone through all of the modules within scikit-learn that we use and checked if there have been API changes since version 1.3 that would affect those modules. As far as I can tell it would be safe to update to version 1.5 (the latest) which would solve the issues with numpy. We would need to use all of the modules using scikit-learn to verify that nothing broke.

**Comment by mkruckow** [comment]
@elizabethteng pointed out, that we might need to do further code updates related to numpy 2, see issue #407 .

**Comment by celiotine** [comment]
Hopefully everything is now working with limiting the numpy version <2.0.0 (PR #410), but I will leave this issue here for discussion.

**Comment by sgossage** [comment]
This issue seems to be resolved in the latest versions from my own testing. @maxbriel, can you confirm?

**Comment by maxbriel** [comment]
@sgossage This was still left open because we should update scikit-learn and numpy, eventually. We just limited the version for now.
@POSYDON-code/posydon-core-developers, we should decide if/when we do this

**Comment by sgossage** [comment]
I changed the issue's title to reflect its current status.
