### ISSUE TITLE
binaries failing with BH spins > 1

### ISSUE THREAD

**Issue by celiotine** [POSYDON-code/POSYDON-public#439]
Some binaries are failing because their calculated BH spins are greater than one. I've noticed that this is happening for spin values ~close to one, so not sure if this is related to rounding at all. This is happening for ~1/15k binaries.

This is the full error:
```
Traceback (most recent call last):
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/popsyn/binarypopulation.py", line 325, in _safe_evolve
    binary.evolve()
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/binary_evol/binarystar.py", line 219, in evolve
    self.run_step()
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/binary_evol/binarystar.py", line 248, in run_step
    next_step(self)
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/binary_evol/SN/step_SN.py", line 425, in __call__
    self.collapse_star(star=binary.star_2)
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/binary_evol/SN/step_SN.py", line 787, in collapse_star
    final_BH = do_core_collapse_BH(
               ^^^^^^^^^^^^^^^^^^^^
  File "/home/cel2717/.conda/envs/posydon-source/lib/python3.11/site-packages/posydon/binary_evol/SN/profile_collapse.py", line 573, in do_core_collapse_BH
    raise ValueError(
ValueError: We got a=1.0017 from shell 1738 containing 0.00035716 M_sun
```
An example binary that produces this error:
```
ini_filepath = /projects/b1119/cliotine/dev_general/debugging/params.ini

star_1 = SingleStar(**{'mass': 18.107506844123645, 'state': 'H-rich_Core_H_burning',
                'natal_kick_array':  [528.2970725443025, 4.190728383757787, 1.1521129697118118, 5.015343794234789]})
star_2 = SingleStar(**{'mass': 15.641392951875442, 'state': 'H-rich_Core_H_burning',
                'natal_kick_array': [None, None, None, None]})
binary = BinaryStar(star_1, star_2, **{'time': 0.0,  'state': 'detached',  'event': 'ZAMS', 
                        'orbital_period':  151.99252706449792,'eccentricity': 0.0}, properties = sim_prop)
```

**Comment by mkruckow** [comment]
I have seen them in tests with the v1 data, too.

Those errors don't happen in the collapse done during the post-processing of the grids. Thus, it is questionable why it happens during the runs, while it requests a profile which can only come from the grids in the current code.

I'm puzzled about this. Is it a case of corrupted data? May due to some precession loss?

**Comment by mkruckow** [comment]
During the pop-syn we only have the down-sampled profiles, while we have the full profiles during the post-processing, that's why we save the spin as extra quantity in the post-processing. Thus, the question might be: Why do we recalculate it during the pop-syn from the profile?
If there is a need to recalculate it, should we replace any values of a>1 coming from down-sampled profiles by 1? With other words capping it at 1 during pop-syn?

**Comment by maxbriel** [comment]
I tried rerunning the binary and didn't get this error. This is using [387f09d](https://github.com/POSYDON-code/POSYDON/pull/502/commits/387f09d0c81b0badd2b068ed55cb5ef86eca25bd).
As you can see below, it reached `step_end`.

There are warnings (see below), but no failure. Since you're using the IF interpolator in your parameters, I wonder if there might be an issue with using the interpolation values and then falling back onto the profile. Although I don't see that issue appear.

@celiotine Do you still get these? If not, feel free to close the issue :D If you still do, please send me some more examples and their population params :) 


<details>
<summary> Warnings </summary>

```
/Users/max/Documents/POSYDON/posydon/utils/common_functions.py:220: EvolutionWarning: 'Trying to compute RL radius for binary with invalid separation'
  Pwarn("Trying to compute RL radius for binary with invalid"
/Users/max/Documents/POSYDON/posydon/utils/common_functions.py:237: EvolutionWarning: 'Trying to compute RL radius for nonexistent object'
  Pwarn("Trying to compute RL radius for nonexistent object",
https://file+.vscode-resource.vscode-cdn.net/Users/max/Documents/POSYDON/posydon/utils/common_functions.py:252: EvolutionWarning: 'Trying to compute RL radius for nonexistent companion'
  Pwarn("Trying to compute RL radius for nonexistent companion",
https://file+.vscode-resource.vscode-cdn.net/Users/max/Documents/POSYDON/posydon/binary_evol/SN/step_SN.py:539: InterpolationWarning: 'MODEL04: The collapsed star was not interpolated! If use_profiles or use_core_masses is set to True, continue with the collapse.'
  Pwarn(f'{MODEL_NAME_SEL}: The collapsed star '
```

</details>



<img width="1074" alt="Image" src="https://github.com/user-attachments/assets/1b6ec18b-6433-418c-8574-c35baee436e3" />

**Comment by celiotine** [comment]
I re-ran the original binary above and it completed ok, and I ran populations of 300k binaries and didn't see the error anymore (all with the IF interpolator and both Sukhbold+16/Fryer+12-delayed SN models, [313315a](https://github.com/POSYDON-code/POSYDON/commit/313315a643fde9beb4aee9b9d0fafe4e0b203451)). So I think it is safe to assume that the issue has been fixed by the POSYDON gods.
